// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCliente = "clientes"

// Cliente mapped from table <clientes>
type Cliente struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Cuit        string `gorm:"column:cuit;not null" json:"cuit"`
	RazonSocial string `gorm:"column:razon_social;not null" json:"razon_social"`
}

// TableName Cliente's table name
func (*Cliente) TableName() string {
	return TableNameCliente
}
