services:
  postgres:
    image: postgres:12-alpine3.18
    env_file:
      - dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    build:
      context: ../../.
      dockerfile: infrastructure/local/Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - dev.env
    depends_on:
      - postgres
    entrypoint: ["/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh"]
    command: ["/app/main"]
volumes:
  postgres:
